# Downsampling testing

In [1]:
import pandas as pd
import numpy as np

### 1) features without TF-IDF

In [2]:
import pandas as pd
import numpy as np
file_name="D:/Group Project/yelp_zip_processed_features.csv"
df=pd.read_csv(file_name,sep="\t")

In [3]:
data=df[['rating','num_word', 'num_noun', 'num_verb',
       'num_adj', 'num_adv', 'num_personal_pronoun', 'avg_word_len',
       'lexical_diversity', 'sentiment', 'typo_ratio', 'emotiveness_ratio',
       'num_positive_words', 'num_negative_words', 'num_clauses',
       'previous_user_reviews', 'avg_user_sentiment', 'avg_user_rating',
       'total_user_reviews', 'user_content_similarity', 'positive_reviews',
       'negative_reviews', 'positive_review_ratio', 'negative_review_ratio',
       'avg_business_sentiment', 'avg_business_rating',
       'total_business_reviews', 'label']]
print(data.head())

   rating  num_word  num_noun  num_verb  num_adj  num_adv  \
0     1.0        35         9         2        5        2   
1     1.0       241        54        31       16       15   
2     3.0        49        11         3        9        2   
3     5.0       216        56        33       19       14   
4     5.0       146        31        23       15        9   

   num_personal_pronoun  avg_word_len  lexical_diversity  sentiment  ...  \
0                     1      5.000000           0.933333  -0.200000  ...   
1                     7      5.561905           0.876190  -0.047619  ...   
2                     1      5.130435           0.913043   0.130435  ...   
3                     5      5.941176           0.756303   0.168067  ...   
4                     8      5.507246           0.840580   0.159420  ...   

   total_user_reviews  user_content_similarity  positive_reviews  \
0                   1             0.000000e+00               0.0   
1                   1             0.0000

In [7]:
fake_reviews=data[data.label==-1]
print(fake_reviews.head())
print("number of fake reviews:",len(fake_reviews))

   rating  num_word  num_noun  num_verb  num_adj  num_adv  \
0     1.0        35         9         2        5        2   
1     1.0       241        54        31       16       15   
2     3.0        49        11         3        9        2   
3     5.0       216        56        33       19       14   
4     5.0       146        31        23       15        9   

   num_personal_pronoun  avg_word_len  lexical_diversity  sentiment  ...  \
0                     1      5.000000           0.933333  -0.200000  ...   
1                     7      5.561905           0.876190  -0.047619  ...   
2                     1      5.130435           0.913043   0.130435  ...   
3                     5      5.941176           0.756303   0.168067  ...   
4                     8      5.507246           0.840580   0.159420  ...   

   total_user_reviews  user_content_similarity  positive_reviews  \
0                   1             0.000000e+00               0.0   
1                   1             0.0000

#### I tried to get the real and fake reviews from original dataset separately, and then randomly select equal number of real reviews out as the number of fake reviews. Finally I combined equal number(80466) of fake reviews with real reviews to generate a balanced dataset (160932 samples).

In [8]:
real_reviews=data[data.label==1]
print(real_reviews.head())
print("number of real reviews:", len(real_reviews))
print(type(real_reviews))

    rating  num_word  num_noun  num_verb  num_adj  num_adv  \
7      1.0        71        18        12        3        7   
8      2.0       265        60        33       21       21   
9      4.0       138        37        15       12       14   
10     3.0       210        46        24       20       18   
11     5.0       108        21        15        9        7   

    num_personal_pronoun  avg_word_len  lexical_diversity  sentiment  ...  \
7                      2      4.864865           0.945946   0.027027  ...   
8                     11      5.721739           0.730435   0.052174  ...   
9                      3      5.684932           0.890411   0.027397  ...   
10                     8      5.975000           0.787500   0.137500  ...   
11                     7      5.288889           0.933333   0.288889  ...   

    total_user_reviews  user_content_similarity  positive_reviews  \
7                    1                 0.000000               0.0   
8                    3    

In [9]:
import random
selected_real_reviews=real_reviews.sample(n=80466, random_state=1)
print("number of selected real reviews:", selected_real_reviews)

number of selected real reviews:         rating  num_word  num_noun  num_verb  num_adj  num_adv  \
455259     4.0       135        37        17       15        9   
507066     5.0        28         8         2        6        2   
267476     4.0        17         6         1        5        0   
112949     4.0       104        22        13        6        7   
481423     5.0        24         6         1        1        0   
...        ...       ...       ...       ...      ...      ...   
14743      4.0        34         9         4        8        1   
31035      3.0       110        18        13       10        9   
479146     5.0        38         4         3        6        5   
343574     4.0        33        10         2        9        0   
256135     5.0        15         4         1        2        1   

        num_personal_pronoun  avg_word_len  lexical_diversity  sentiment  ...  \
455259                     5      5.786667           0.840000   0.080000  ...   
507066      

In [85]:
data_join=pd.concat([fake_reviews, selected_real_reviews])
print(data_join.head())
print(len(data_join))

   rating  num_word  num_noun  num_verb  num_adj  num_adv  \
0     1.0        35         9         2        5        2   
1     1.0       241        54        31       16       15   
2     3.0        49        11         3        9        2   
3     5.0       216        56        33       19       14   
4     5.0       146        31        23       15        9   

   num_personal_pronoun  avg_word_len  lexical_diversity  sentiment  ...  \
0                     1      5.000000           0.933333  -0.200000  ...   
1                     7      5.561905           0.876190  -0.047619  ...   
2                     1      5.130435           0.913043   0.130435  ...   
3                     5      5.941176           0.756303   0.168067  ...   
4                     8      5.507246           0.840580   0.159420  ...   

   total_user_reviews  user_content_similarity  positive_reviews  \
0                   1             0.000000e+00               0.0   
1                   1             0.0000

In [11]:
import sklearn.metrics as metrics
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, f1_score, recall_score
from sklearn.svm import SVC, LinearSVC
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [9]:
!pip install imblearn

In [24]:
import imblearn
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline

In [86]:
x_data=data_join[['rating','num_word', 'num_noun', 'num_verb',
       'num_adj', 'num_adv', 'num_personal_pronoun', 'avg_word_len',
       'lexical_diversity', 'sentiment', 'typo_ratio', 'emotiveness_ratio',
       'num_positive_words', 'num_negative_words', 'num_clauses',
       'previous_user_reviews', 'avg_user_sentiment', 'avg_user_rating',
       'total_user_reviews', 'user_content_similarity', 'positive_reviews',
       'negative_reviews', 'positive_review_ratio', 'negative_review_ratio',
       'avg_business_sentiment', 'avg_business_rating',
       'total_business_reviews']]
print(x_data)
y_data=data_join[['label']].values.ravel()

        rating  num_word  num_noun  num_verb  num_adj  num_adv  \
0          1.0        35         9         2        5        2   
1          1.0       241        54        31       16       15   
2          3.0        49        11         3        9        2   
3          5.0       216        56        33       19       14   
4          5.0       146        31        23       15        9   
...        ...       ...       ...       ...      ...      ...   
14743      4.0        34         9         4        8        1   
31035      3.0       110        18        13       10        9   
479146     5.0        38         4         3        6        5   
343574     4.0        33        10         2        9        0   
256135     5.0        15         4         1        2        1   

        num_personal_pronoun  avg_word_len  lexical_diversity  sentiment  ...  \
0                          1      5.000000           0.933333  -0.200000  ...   
1                          7      5.561905   

In [74]:
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [87]:
selected_features=['num_word', 'num_noun', 'num_verb',
       'num_adj', 'num_adv', 'num_personal_pronoun', 'avg_word_len',
       'lexical_diversity', 'sentiment', 'typo_ratio', 'emotiveness_ratio',
       'num_positive_words', 'num_negative_words', 'num_clauses',
       'previous_user_reviews', 'avg_user_sentiment', 'avg_user_rating',
       'total_user_reviews', 'user_content_similarity', 'positive_reviews',
       'negative_reviews', 'positive_review_ratio', 'negative_review_ratio',
       'avg_business_sentiment', 'avg_business_rating',
       'total_business_reviews']
print(len(selected_features))

26


In [58]:
#x_train, x_test, y_train, y_test=train_test_split(x_data,y_data,test_size=0.3,shuffle=True, random_state=2)

In [59]:
#scaler=StandardScaler().fit(x_train)
#scaled_x_train=scaler.transform(x_train)
#scaled_x_test=scaler.transform(x_test)

In [88]:
%%time
# Baseline model without any direct representation of words or word embeddings

# Using a linear kernel for now as I have seen pretty good results for linear SVM with text classification
# Using LinearSVC for better performance on large data sets
baseline_svm = LinearSVC(C=1)

# Best practice scale data when using geometric based models like SVM where magnitude is important
scaler = StandardScaler()
X_train, X_test, y_train, y_test = train_test_split(x_data,
                                                    y_data,
                                                    test_size=.3,
                                                    random_state=24)

# Using imblearn pipeline to manage the scaling and resampling logic in a simple way
svm_pipe = Pipeline([('scaler', scaler),
                     ('svc', baseline_svm)])

svm_pipe.fit(X_train, y_train)

CPU times: total: 34.7 s
Wall time: 34.8 s


F:\Anaconda\lib\site-packages\sklearn\svm\_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


Pipeline(steps=[('scaler', StandardScaler()), ('svc', LinearSVC(C=1))])

In [91]:
preds = svm_pipe.predict(X_test)

In [92]:
print(metrics.classification_report(y_test, preds))

              precision    recall  f1-score   support

          -1       0.68      0.80      0.74     24197
           1       0.76      0.62      0.68     24083

    accuracy                           0.71     48280
   macro avg       0.72      0.71      0.71     48280
weighted avg       0.72      0.71      0.71     48280



In [127]:
matrix1 = confusion_matrix(y_test, preds)
print(matrix1)
print(matrix1.diagonal()/matrix1.sum(axis=1))

[[19415  4665]
 [ 9284 14916]]
[0.80627076 0.61636364]


In [ ]:
%%time
from sklearn.model_selection import GridSearchCV
param_grid = {'C': [0.0001,0.001, 0.01, 0.1,1, 10, 100], 'gamma': [1,0.1,0.01,0.001],'kernel': ['poly','rbf', 'sigmoid','linear']}
#param_grid = {'C':np.arange(0.001,1,20)}
search = GridSearchCV(SVC(),param_grid,cv=5,return_train_score=True)
search.fit(x_train,y_train)

### Down-sampling using TF-IDF features

In [14]:
%%time
vectorizer = TfidfVectorizer()
import string
import nltk
from nltk.tokenize import word_tokenize
data2=df.copy()
data2['word_list']=np.nan
for i in range(len(data2)):
    lemma=data2.lemma.iloc[i]
    try:
        l=(word_tokenize(lemma))
        data2.word_list.iloc[i]=l
    except:
        data2.word_list.iloc[i]=[]

<timed exec>:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


CPU times: total: 4min 11s
Wall time: 4min 12s


In [15]:
data2=data2.fillna('')
vectorizer.fit(data2.lemma)

TfidfVectorizer()

In [16]:
label_col = 'label'

In [17]:
fake_reviews2=data2[data2.label==-1]
#print(fake_reviews2.head())
print("number of fake reviews:",len(fake_reviews2))

number of fake reviews: 80466


In [18]:
real_reviews2=data2[data2.label==1]
#print(real_reviews2.head())
print("number of real reviews2:", len(real_reviews2))
print(type(real_reviews2))

number of real reviews2: 528132
<class 'pandas.core.frame.DataFrame'>


In [19]:
selected_real_reviews2=real_reviews2.sample(n=80466, random_state=1)
print("number of selected real reviews:", len(selected_real_reviews2))

number of selected real reviews: 80466


In [20]:
data_join2=pd.concat([fake_reviews2, selected_real_reviews2])
#print(data_join.head())
print(len(data_join2))

160932


In [30]:
x_data2=data_join2[['lemma']]
print(x_data2)
y_data2=data_join2[['label']].values.ravel()

                                                    lemma
0       drink bad hot chocolate water latte burn taste...
1       bad experience casual coffee light fare place ...
2       locate site old spruce st video mild cofee goo...
3       enjoy coffee breakfast twice toast recent visi...
4       love toast food choice fantastic love serve br...
...                                                   ...
14743   worth try bread fresh meat dry green pepper go...
31035   climb aboard phooooo train pho train pretty pa...
479146  icecream amazing thing ve ve icecream deliciou...
343574  share black taglierini creamy taglierini garli...
256135         long nite great lamb rice white sauce yumm

[160932 rows x 1 columns]


In [22]:
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [82]:
%%time
tfidf_svm = LinearSVC(C=1)

X_train2, X_test2, y_train2, y_test2 = train_test_split(data_join2.lemma,
                                                    data_join2[label_col].values,
                                                    test_size=.3,
                                                    random_state=24)

# Using imblearn pipeline to manage the resampling logic in a simple way
tfidf_svm_pipe = Pipeline([('svc', tfidf_svm)])

tfidf_x_train = vectorizer.transform(X_train2)
tfidf_x_test = vectorizer.transform(X_test2)

print(tfidf_x_train.shape)
print(tfidf_x_test.shape)

(112652, 151750)
(48280, 151750)
CPU times: total: 7.27 s
Wall time: 8.16 s


In [83]:
%%time
tfidf_svm_pipe.fit(tfidf_x_train, y_train2)

CPU times: total: 2.84 s
Wall time: 2.89 s


Pipeline(steps=[('svc', LinearSVC(C=1))])

In [84]:
tfidf_preds = tfidf_svm_pipe.predict(tfidf_x_test)

print(metrics.classification_report(y_test2, tfidf_preds))
metrics.confusion_matrix(y_test2, tfidf_preds)

              precision    recall  f1-score   support

          -1       0.66      0.66      0.66     24197
           1       0.66      0.65      0.65     24083

    accuracy                           0.66     48280
   macro avg       0.66      0.66      0.66     48280
weighted avg       0.66      0.66      0.66     48280



array([[16078,  8119],
       [ 8467, 15616]], dtype=int64)

In [118]:
matrix2 = confusion_matrix(y_test2, tfidf_preds)
print(matrix2)
print(matrix2.diagonal()/matrix.sum(axis=1))

[[16078  8119]
 [ 8467 15616]]
[0.66446254 0.6484242 ]


### Down-sampling of TF-IDF with features

In [29]:
filtered_features = ['rating','num_word', 'num_noun', 'num_verb',
       'num_adj', 'num_adv', 'num_personal_pronoun', 'avg_word_len',
       'lexical_diversity', 'sentiment', 'typo_ratio', 'emotiveness_ratio',
       'num_positive_words', 'num_negative_words', 'num_clauses',
       'previous_user_reviews', 'avg_user_sentiment', 'avg_user_rating',
       'total_user_reviews', 'user_content_similarity', 'positive_reviews',
       'negative_reviews', 'positive_review_ratio', 'negative_review_ratio',
       'avg_business_sentiment', 'avg_business_rating',
       'total_business_reviews']

In [31]:
print(data_join2[filtered_features].shape)

(160932, 27)


In [44]:
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import ComplementNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import CategoricalNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [74]:
%%time
from sklearn.compose import ColumnTransformer

tfidf_combined_svm = LinearSVC(C=1)
X_train3, X_test3, y_train3, y_test3 = train_test_split(data_join2[filtered_features + ['lemma']],
                                                    data_join2[label_col].values,
                                                    test_size=.3,
                                                    random_state=24)

summary_pipeline = Pipeline([('scaler', StandardScaler())])
tfidf_pipeline = Pipeline([('vectorizer', TfidfVectorizer(analyzer='word', ngram_range=(1,1)))])
column_processor = ColumnTransformer([('summary', summary_pipeline, filtered_features),
                                      ('tfidf', tfidf_pipeline, 'lemma')])


tfidf_combined_svm_pipe = Pipeline([('preprocessing', column_processor),
                                    ('svc', tfidf_combined_svm)])


print(X_train3.shape)
print(X_test3.shape)
tfidf_combined_svm_pipe

(112652, 28)
(48280, 28)
CPU times: total: 609 ms
Wall time: 3.09 s


Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('summary',
                                                  Pipeline(steps=[('scaler',
                                                                   StandardScaler())]),
                                                  ['rating', 'num_word',
                                                   'num_noun', 'num_verb',
                                                   'num_adj', 'num_adv',
                                                   'num_personal_pronoun',
                                                   'avg_word_len',
                                                   'lexical_diversity',
                                                   'sentiment', 'typo_ratio',
                                                   'emotiveness_ratio',
                                                   'num_positive_words',
                                                   'num_negative_words',
         

In [75]:
%%time
tfidf_combined_svm_pipe.fit(X_train3, y_train3)

CPU times: total: 59.4 s
Wall time: 59.8 s


F:\Anaconda\lib\site-packages\sklearn\svm\_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('summary',
                                                  Pipeline(steps=[('scaler',
                                                                   StandardScaler())]),
                                                  ['rating', 'num_word',
                                                   'num_noun', 'num_verb',
                                                   'num_adj', 'num_adv',
                                                   'num_personal_pronoun',
                                                   'avg_word_len',
                                                   'lexical_diversity',
                                                   'sentiment', 'typo_ratio',
                                                   'emotiveness_ratio',
                                                   'num_positive_words',
                                                   'num_negative_words',
         

In [76]:
tfidf_combined_preds = tfidf_combined_svm_pipe.predict(X_test3)

print(metrics.classification_report(y_test3, tfidf_combined_preds))
#metrics.confusion_matrix(y_test3, tfidf_combined_preds)

              precision    recall  f1-score   support

          -1       0.70      0.74      0.72     24197
           1       0.72      0.68      0.70     24083

    accuracy                           0.71     48280
   macro avg       0.71      0.71      0.71     48280
weighted avg       0.71      0.71      0.71     48280



In [117]:
matrix3 = confusion_matrix(y_test3, tfidf_combined_preds)
print(matrix3)
print(matrix3.diagonal()/matrix.sum(axis=1))

[[17862  6335]
 [ 7758 16325]]
[0.73819068 0.67786405]


### a) SVC() model, gamma='auto'

### SVC parameters: kernel: {‘linear’, ‘poly’, ‘rbf’, ‘sigmoid’, ‘precomputed’} or callable, default=’rbf’
### gamma{‘scale’, ‘auto’} or float, default=’scale’
### class_weight: dict or ‘balanced’, default=None
### decision_function_shape{‘ovo’, ‘ovr’}, default=’ovr’. The parameter is ignored for binary classification.

In [19]:
%%time
svc=SVC(gamma='auto')
svc.fit(scaled_x_train,y_train)
y_predict_train=svc.predict(scaled_x_train)
y_predict_test=svc.predict(scaled_x_test)

Wall time: 36min 30s


In [27]:
from sklearn.metrics import accuracy_score, precision_score, f1_score, recall_score, classification_report,confusion_matrix
train_accuracy=accuracy_score(y_train,y_predict_train)
print(train_accuracy)

0.6411071263714803


In [28]:
test_accuracy=accuracy_score(y_test,y_predict_test)
print(test_accuracy)

0.6367232808616404


In [29]:
print("accuracy score:",accuracy_score(y_test,y_predict_test))
print("precision score:",precision_score(y_test,y_predict_test))
print("F1 score:",f1_score(y_test,y_predict_test))
print("recall score:",recall_score(y_test,y_predict_test))

accuracy score: 0.6367232808616404
precision score: 0.6449745353240761
F1 score: 0.6281983337926357
recall score: 0.6122727272727273


In [31]:
CM=confusion_matrix(y_test,y_predict_test)
print(CM)

[[15924  8156]
 [ 9383 14817]]


In [33]:
print(metrics.classification_report(y_test, y_predict_test))

              precision    recall  f1-score   support

          -1       0.63      0.66      0.64     24080
           1       0.64      0.61      0.63     24200

    accuracy                           0.64     48280
   macro avg       0.64      0.64      0.64     48280
weighted avg       0.64      0.64      0.64     48280



### gamma='auto', kernel='linear', c=0.01

In [40]:
%%time
svc=SVC(gamma='auto',kernel='linear',C=0.01)
svc.fit(scaled_x_train,y_train)
y_predict_train=svc.predict(scaled_x_train)
y_predict_test=svc.predict(scaled_x_test)

CPU times: total: 18min 4s
Wall time: 18min 7s


In [41]:
print("accuracy score:",accuracy_score(y_test,y_predict_test))
print("precision score:",precision_score(y_test,y_predict_test))
print("F1 score:",f1_score(y_test,y_predict_test))
print("recall score:",recall_score(y_test,y_predict_test))
CM=confusion_matrix(y_test,y_predict_test)
print(CM)
print(metrics.classification_report(y_test, y_predict_test))

accuracy score: 0.5900787075393538
precision score: 0.623452987623901
F1 score: 0.5294243526642415
recall score: 0.4600413223140496
[[17356  6724]
 [13067 11133]]
              precision    recall  f1-score   support

          -1       0.57      0.72      0.64     24080
           1       0.62      0.46      0.53     24200

    accuracy                           0.59     48280
   macro avg       0.60      0.59      0.58     48280
weighted avg       0.60      0.59      0.58     48280



### gamma='auto', kernel='rbf', c=0.01

In [42]:
%%time
svc=SVC(gamma='auto',kernel='rbf',C=0.01)
svc.fit(scaled_x_train,y_train)
y_predict_train=svc.predict(scaled_x_train)
y_predict_test=svc.predict(scaled_x_test)

CPU times: total: 40min 14s
Wall time: 40min 21s


In [43]:
print("accuracy score:",accuracy_score(y_test,y_predict_test))
print("precision score:",precision_score(y_test,y_predict_test))
print("F1 score:",f1_score(y_test,y_predict_test))
print("recall score:",recall_score(y_test,y_predict_test))
CM=confusion_matrix(y_test,y_predict_test)
print(CM)
print(metrics.classification_report(y_test, y_predict_test))

accuracy score: 0.6321872410936206
precision score: 0.6442712532473349
F1 score: 0.6183209388299016
recall score: 0.5943801652892562
[[16138  7942]
 [ 9816 14384]]
              precision    recall  f1-score   support

          -1       0.62      0.67      0.65     24080
           1       0.64      0.59      0.62     24200

    accuracy                           0.63     48280
   macro avg       0.63      0.63      0.63     48280
weighted avg       0.63      0.63      0.63     48280



### gamma='auto', kernel='poly', c=0.01

In [44]:
%%time
svc=SVC(gamma='auto',kernel='poly',C=0.01)
svc.fit(scaled_x_train,y_train)
y_predict_train=svc.predict(scaled_x_train)
y_predict_test=svc.predict(scaled_x_test)

CPU times: total: 20min 48s
Wall time: 20min 49s


In [45]:
print("accuracy score:",accuracy_score(y_test,y_predict_test))
print("precision score:",precision_score(y_test,y_predict_test))
print("F1 score:",f1_score(y_test,y_predict_test))
print("recall score:",recall_score(y_test,y_predict_test))
CM=confusion_matrix(y_test,y_predict_test)
print(CM)
print(metrics.classification_report(y_test, y_predict_test))

accuracy score: 0.576222038111019
precision score: 0.5461751197590005
F1 score: 0.683761476398034
recall score: 0.9140082644628099
[[ 5701 18379]
 [ 2081 22119]]
              precision    recall  f1-score   support

          -1       0.73      0.24      0.36     24080
           1       0.55      0.91      0.68     24200

    accuracy                           0.58     48280
   macro avg       0.64      0.58      0.52     48280
weighted avg       0.64      0.58      0.52     48280



### b) SVC() model, hyperparameter tuning

In [ ]:
%%time
from sklearn.model_selection import cross_val_score, GridSearchCV, cross_validate, train_test_split
svm_parameters = {'kernel':('linear', 'rbf'), 'C':[0.01, 0.1, 1.0]}
svm_cv=GridSearchCV(SVC(gamma='auto'),svm_parameters,n_jobs=-1, return_train_score=True)
svm_cv.fit(scaled_x_train,y_train)
best_score=svm_cv.best_score_
print(best_score)

In [ ]:
svm_cv.fit(scaled_x_train,y_train)
y_predict_train=svm_cv.predict(scaled_x_train)
y_predict_test=svm_cv.predict(scaled_x_test)

In [ ]:
print("accuracy score:",accuracy_score(y_test,y_predict_test))
print("precision score:",precision_score(y_test,y_predict_test))
print("F1 score:",f1_score(y_test,y_predict_test))
print("recall score:",recall_score(y_test,y_predict_test))

### c) LinearSCV()

In [68]:
from sklearn.svm import LinearSVC
linear_svc=LinearSVC()
linear_svc.fit(scaled_x_train,y_train)
y_predict_train=linear_svc.predict(scaled_x_train)
y_predict_test=linear_svc.predict(scaled_x_test)

F:\Anaconda\lib\site-packages\sklearn\svm\_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


In [70]:
from sklearn.metrics import roc_auc_score
print("accuracy score:",accuracy_score(y_test,y_predict_test))
print("precision score:",precision_score(y_test,y_predict_test))
print("F1 score:",f1_score(y_test,y_predict_test))
print("recall score:",recall_score(y_test,y_predict_test))
print("AUC score:",roc_auc_score(y_test,y_predict_test))

accuracy score: 0.5945111847555924
precision score: 0.6080190663115099
F1 score: 0.5706704094388035
recall score: 0.5376446280991736
AUC score: 0.5946528788336399


In [34]:
CM=confusion_matrix(y_test,y_predict_test)
print(CM)

[[15686  8394]
 [11181 13019]]


In [35]:
print(metrics.classification_report(y_test, y_predict_test))

              precision    recall  f1-score   support

          -1       0.58      0.65      0.62     24080
           1       0.61      0.54      0.57     24200

    accuracy                           0.59     48280
   macro avg       0.60      0.59      0.59     48280
weighted avg       0.60      0.59      0.59     48280



In [51]:
fake_reviews_list_words=preprocessed_data[preprocessed_data.label==-1]
print(fake_reviews_list_words.head())

   user_id  prod_id  rating  label  \
0     5044        0     1.0     -1   
1     5045        0     1.0     -1   
2     5046        0     3.0     -1   
3     5047        0     5.0     -1   
4     5048        0     5.0     -1   

                                          list_words  num_of_words  \
0  ['drink', 'bad', 'hot', 'chocolate', 'water', ...            17   
1  ['bad', 'experience', 'ever', 'casual', 'coffe...           115   
2  ['locate', 'site', 'old', 'spruce', 'street', ...            24   
3  ['enjoy', 'coffee', 'breakfast', 'twice', 'toa...           128   
4  ['love', 'toast', 'food', 'choice', 'fantastic...            77   

   num_of_verbs  avg_word_len  emotiveness  num_positive  num_negative  \
0             2      4.882353     0.416667             1             5   
1            17      5.452174     0.379747             4            12   
2             3      5.291667     0.600000             4             1   
3            15      5.664062     0.465116            

In [56]:
real_reviews_list_words=preprocessed_data[preprocessed_data.label==1]
real_reviews_list_words=real_reviews_list_words.sample(n=80466, random_state=1)
print(len(real_reviews_list_words))
#print(real_reviews_list_words.head())

80466


In [57]:
data2=pd.concat([fake_reviews_list_words,real_reviews_list_words])[['rating', 'list_words','num_of_words',
                 'num_of_verbs','avg_word_len','emotiveness','num_positive','num_negative','sentiment','label']]
print(data2.head())

   rating                                         list_words  num_of_words  \
0     1.0  ['drink', 'bad', 'hot', 'chocolate', 'water', ...            17   
1     1.0  ['bad', 'experience', 'ever', 'casual', 'coffe...           115   
2     3.0  ['locate', 'site', 'old', 'spruce', 'street', ...            24   
3     5.0  ['enjoy', 'coffee', 'breakfast', 'twice', 'toa...           128   
4     5.0  ['love', 'toast', 'food', 'choice', 'fantastic...            77   

   num_of_verbs  avg_word_len  emotiveness  num_positive  num_negative  \
0             2      4.882353     0.416667             1             5   
1            17      5.452174     0.379747             4            12   
2             3      5.291667     0.600000             4             1   
3            15      5.664062     0.465116            20             4   
4            11      5.337662     0.520000            12             1   

   sentiment  label  
0  -0.235294     -1  
1  -0.069565     -1  
2   0.125000     -1 

In [58]:
vectorizer = TfidfVectorizer()
vectorizer.fit(data2.list_words)

TfidfVectorizer()

In [59]:
x_data=data2.list_words
y_data=data2.label.values.ravel()

In [60]:
x_train, x_test, y_train, y_test=train_test_split(x_data,y_data,test_size=0.3,shuffle=True, random_state=2)

In [61]:
tfidf_x_train = vectorizer.transform(x_train)
tfidf_x_test = vectorizer.transform(x_test)

In [64]:
%%time
tfidf_svm = LinearSVC()
tfidf_svm.fit(tfidf_x_train,y_train)
y_predict_train=tfidf_svm.predict(tfidf_x_train)
y_predict_test=tfidf_svm.predict(tfidf_x_test)

CPU times: total: 2.75 s
Wall time: 2.76 s


In [65]:
print("accuracy score:",accuracy_score(y_test,y_predict_test))
print("precision score:",precision_score(y_test,y_predict_test))
print("F1 score:",f1_score(y_test,y_predict_test))
print("recall score:",recall_score(y_test,y_predict_test))
CM=confusion_matrix(y_test,y_predict_test)
print(CM)
print(metrics.classification_report(y_test, y_predict_test))

accuracy score: 0.6553231151615576
precision score: 0.6614274121214709
F1 score: 0.6504946128158277
recall score: 0.6399173553719009
[[16153  7927]
 [ 8714 15486]]
              precision    recall  f1-score   support

          -1       0.65      0.67      0.66     24080
           1       0.66      0.64      0.65     24200

    accuracy                           0.66     48280
   macro avg       0.66      0.66      0.66     48280
weighted avg       0.66      0.66      0.66     48280



In [66]:
%%time
svc=SVC(gamma='auto',kernel='poly',C=0.01)
svc.fit(tfidf_x_train,y_train)
y_predict_train=svc.predict(tfidf_x_train)
y_predict_test=svc.predict(tfidf_x_test)

CPU times: total: 2h 58min 59s
Wall time: 2h 59min 11s


In [67]:
print("accuracy score:",accuracy_score(y_test,y_predict_test))
print("precision score:",precision_score(y_test,y_predict_test))
print("F1 score:",f1_score(y_test,y_predict_test))
print("recall score:",recall_score(y_test,y_predict_test))
CM=confusion_matrix(y_test,y_predict_test)
print(CM)
print(metrics.classification_report(y_test, y_predict_test))

accuracy score: 0.4987572493786247
precision score: 0.0
F1 score: 0.0
recall score: 0.0
[[24080     0]
 [24200     0]]
              precision    recall  f1-score   support

          -1       0.50      1.00      0.67     24080
           1       0.00      0.00      0.00     24200

    accuracy                           0.50     48280
   macro avg       0.25      0.50      0.33     48280
weighted avg       0.25      0.50      0.33     48280



F:\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
F:\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
F:\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
F:\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-scor

In [73]:
print(tfidf_x_train.shape)

(112652, 72088)
